# For Bakecode Development

# Command: docker build . -t bakecode:dev --file Dockerfile.dev

FROM dart:latest

# Copy bakecode source

COPY . /bakecode

# Get dependencies

RUN cd /bakecode && dart pub get

# Run pubspec_extract builder

RUN dart pub global activate pubspec_extract

RUN cd /bakecode && dart pub global run pubspec_extract -d lib/pubspec.g.dart

CMD [ "dart" , "/bakecode/bin/bakecode.dart" , "launch"]
