# For Bakecode Development

# Command: docker build . -t bakecode:dev --file Dockerfile.dev

FROM dart:latest

# Copy bakecode source

COPY . /bakecode

WORKDIR /bakecode

# Get dependencies

RUN pub get

# Run pubspec_extract builder

RUN pub global activate pubspec_extract

RUN pub global run pubspec_extract -d lib/pubspec.g.dart

CMD [ "dart" , "bin/bakecode.dart" , "launch"]
